# Generated by Django 4.1.7 on 2023-03-31 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=100, verbose_name='Cell Name')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, verbose_name='Gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Profile Picture')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.cell', verbose_name='Cell')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.district', verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Property Title')),
                ('description', models.TextField(verbose_name='Property Description')),
                ('bedrooms', models.IntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(verbose_name='Bathrooms')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Is funished')),
                ('floors', models.IntegerField(verbose_name='Floors')),
                ('plot_size', models.CharField(max_length=50, verbose_name='Plot Size')),
                ('renting_price', models.FloatField(verbose_name='Renting Price')),
                ('status', models.BooleanField(verbose_name='Available')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Published Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('street', models.CharField(max_length=50, verbose_name='Street Address')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.cell', verbose_name='Cell')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.district', verbose_name='District')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.landlord', verbose_name='Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='Property Type')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100, verbose_name='Province Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, verbose_name='Sector Name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='renting.district', verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField(verbose_name='Payment Amount')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.landlord', verbose_name='Landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.property', verbose_name='Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(upload_to='properties', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Property Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='renting.property', verbose_name='Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.propertytype', verbose_name='Property Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='property',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.sector', verbose_name='Sector'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, verbose_name='Gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Profile Picture')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.district', verbose_name='District')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.province', verbose_name='Province')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.sector', verbose_name='Sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='renting.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='renting.district', verbose_name='Sector'),
        ),
    ]
